### Send short URL
POST localhost:1453/short
Content-type: application/json

{
  "url": "https://example.com/web"
}

### Send long URL
POST localhost:1453/long
Content-type: application/json

{
  "url": ""
}

### Send short URL
POST localhost:1453/short
Content-type: application/json

{
  "url": "link2"
}

### Send long URL
POST localhost:1453/long
Content-type: application/json

{
  "url": "link2"
}
